# Stage 1: Build Angular
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# Stage 2: Nginx
FROM nginx:alpine

# 🔥 IMPORTANT: copy from browser folder
COPY --from=build /app/dist/sourya_pg/browser /usr/share/nginx/html

# nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]