services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./uploads:/app/uploads
    environment:
      MYSQLHOST: tramway.proxy.rlwy.net
      MYSQLPORT: 38737
      MYSQLDATABASE: railway
      MYSQLUSER: root
      MYSQLPASSWORD: qmdNMYCVMMnZubIpExCRslIamNsjbOVD
    ports:
      - "8083:8080"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4303:80"